# Docker ortamı için override
spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/fintech_db?currentSchema=transaction_service
  kafka:
    bootstrap-servers: kafka:29092

clients:
  account-service:
    base-url: http://account-service:8082

eureka:
  instance:
    hostname: transaction-service
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.fintech.transaction: INFO
